site_name: "MaximumSettings Wiki"

plugins:
  - awesome-pages
  - search

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - navigation.path
    - content.tabs.link

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  # Extensions


  markdown_extensions:
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    
